### ISSUE TITLE
Enable object-curly-spacing rule

### ISSUE THREAD

**Issue by ksstott** [NewOrbit/eslint-config#149]
In this config we have explicitly switched off the [object-curly-spacing](https://eslint.org/docs/rules/object-curly-spacing). 
Looks like this has always been the case in this config most likely because it was not a rule that existed/was enable on the old ts-lint config.

I suggest that this would be a good rule for us to adopt for consistent code style and hopefully easy to adopt as there is a fixer for the rule too that will fix most/all of existing violations.

**Comment by hisuwh** [comment]
Presumably your suggesting setting this to "always".  I think this is a good idea.  Do you want to send a PR?

**Comment by ksstott** [comment]
> Presumably your suggesting setting this to "always". I think this is a good idea. Do you want to send a PR?

Yes and Yes that's the plan. 😃

**Comment by hisuwh** [comment]
🥇
