### ISSUE TITLE
no-nested-ternary linting rule

### ISSUE THREAD

**Issue by thyde1** [NewOrbit/eslint-config#770]
This seems like a sensible rule to introduce.

To copy directly from the following link:

> Nesting ternary expressions can make code more difficult to understand.
e.g. `var foo = bar ? baz : qux === quxx ? bing : bam;`

https://eslint.org/docs/latest/rules/no-nested-ternary

**Comment by hawkzey** [comment]
omg please, I hate it when I see this

**Comment by Senderek** [comment]
PR: https://github.com/NewOrbit/eslint-config/pull/771
Reviews appreciated.
